# Generated by Django 5.1.1 on 2024-09-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_filmsmodel_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmsmodel',
            name='actors',
        ),
    ]
